# Generated by Django 5.0.6 on 2024-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalhadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_trab', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('fone', models.CharField(max_length=12)),
                ('data_nasc', models.DateTimeField(blank=True)),
                ('endereco', models.TextField()),
                ('email', models.EmailField(max_length=70)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
